version: 0.1.{build}

os: Visual Studio 2015 RC

configuration:
  - Debug
  - Release

environment:
  matrix:
    - VS_PLATFORM: win32
    - VS_PLATFORM: x64

before_build:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmake -H. -Bbuild -G "Visual Studio 14" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM%

build:
  project: build\harpoon.sln
  parallel: true
  verbosity: minimal
